- Crypto.php
> Use openssl instead of mcrypt.

- .travis.yml
- README.md
Only supported PHP versions should be covered cc @ircmaxell :)
> Remove Support for PHP 5.2 and PHP 5.3

- Crypto.php
Make `mcrypt_create_iv()` optional.
> Use openssl_ for CSPRNG

- composer.json
Depends on #40 -- also add some more keywords for Packagist.
> Remove mcrypt dependency from composer.json

- src/Crypto.php
- test.sh
- tests/encode.php
[Referenced implementation](https://github.com/jedisct1/libsodium/blob/b2dd3453d57dc3a98b9704e3fd1326483ed4e47b/src/libsodium/sodium/utils.c#L99-L180).
> Contant-Time bin2hex/hex2bin -- closes #18 #60

- src/Crypto.php
this code is now in runtimeTest()
> removed duplicate code

- src/Exception/CannotPerformOperationException.php
> Fix class name for CannotPerformOperationException

- src/Crypto.php
https://github.com/phpseclib/phpseclib/issues/761
> Version 1.x - Cache-timing safety

- autoload.php
- src/Core.php
- src/random_compat/byte_safe_strings.php
- src/random_compat/cast_to_int.php
- src/random_compat/error_polyfill.php
- src/random_compat/random.php
- src/random_compat/random_bytes_com_dotnet.php
- src/random_compat/random_bytes_dev_urandom.php
- src/random_compat/random_bytes_libsodium.php
- src/random_compat/random_bytes_libsodium_legacy.php
- src/random_compat/random_bytes_mcrypt.php
- src/random_compat/random_int.php
We're explicitly NOT using composer for this because we need it to land in the .phar
Fixes #68
> Add random_compat

- .php_cs
- test/unit/CryptoTest.php
- test/unit/EncodingTest.php
- test/unit/KeyTest.php
> Phpcs fixes

- dist/box.json
- test.sh
disable shebang creation. see #269
> phar shebang disable

- src/File.php
> Check if stream_set_*_buffer exists before invoking

- docs/Tutorial.md
> Add use declarations to Tutorial

- composer.json
I think you might use PSR-4 autoloading. Classes are in correct places.
> WIP: composer: use PSR-4 autoload

- README.md
I wrote a simple file encrypt/decrypt example [fileencrypt](https://github.com/tsusanka/fileencrypt), quite similar to yours [encutil](https://github.com/defuse/encutil).
It uses Symfony Console interface so it can have a litte bit of additional value. Feel free to include it in your Readme if desired.
> Another example project to Readme

- src/Crypto.php
> Fix order of hash_equals comparison

- src/Core.php
Fixes #330: using \hash_hkdf() when possible
> Fix for issue 330

- docs/InstallingAndVerifying.md
> Add autoloader instructions to install docs

- src/Crypto.php
- test/unit/CryptoTest.php
Similar to what was suggested in #349.
> Ensure public API is strictly typed.

- .travis.yml
- composer.json
According to the README.md   https://github.com/defuse/php-encryption#php-encryption
> moved to php 5.6 minimum

- docs/Tutorial.md
> Fix insecure session recommendation

- README.md
PHP 7.3 does not receive security support any more 🤓
> Change minimum recommended version

- .github/workflows/ci.yml
- README.md
When this does get merged, there will be some toggling to do with protected branches, etc.
Motivation: Travis CI is largely broken and slow. For organizations, it's totally borked.
> Migrate from Travis CI to Github Actions
