- .travis.yml
Some minor improvements for Travis.
< PHP 5.4 is not supported so no need to test this, and use sudo to speed-up the boot process.
*Please ignore the typo in the branch-name...*
> remove unsupported php version from travis.yml

- src/Crypto.php
In the `plainDecrypt` method we actually are ensuring that the method `openssl_encrypt` is available but what we use later is `openssl_decrypt`.
> Ensure that openssl_decrypt is available instead of openssl_encrypt

- autoload.php
Replaces #96 (also updated classmap)
> Harden the autoloader against unserialize -> LFI risks

- src/File.php
- src/StreamInterface.php
- test/stream/decrypt.php
- test/stream/encrypt.php
- test/stream/error.php
- test/stream/keygen.php
> Prevent partial reads/writes

- src/Core.php
- src/Key.php
- src/RuntimeTests.php
Remove unused "use" statements
Add docblocks
Fix a spelling error
> Minor Boyscouting for v2.0

- src/ExceptionHandler.php
Without this, IDEs (such as PHPStorm) display an error:
`The thrown object must be an instance of the Exception or Throwable.`
> Fix rethrow class member type.

- src/Crypto.php
- src/KeyOrPassword.php
- test/unit/CryptoTest.php
- test/unit/PasswordTest.php
> Prehash the password before PBKDF2

- src/RuntimeTests.php
This is related to #277 (it doesn't fix the problem, because we can't, but hopefully it will be clearer for others why the exception is being thrown).
> Expand cipher mode not supported exception message.

- README.md
because github renders it as html and it messes up gpg separators
alternative would be to rename the file to have .txt extension
> use raw link to gpg key

- .gitattributes
Downloading php-encryption via Composer takes too much time for a 232KB library. This is because tests, having 13 MB of files, are including in the package. It is very inconvenient in CI environments or for user of projects that use php-encryption, as it takes time, band-width etc..
A user of the library doesn't need theses tests.
> Don't export test for Composer package

- .php_cs
- random_compat is no longer in sourcetree
- the "other" dir was obliterated
- skip composer "vendor" instead
ps: "dist" dir does not to be excluded, as it does not contain `*.php` files
ps2:  two files need php-cs fix:
```
1) KeyProtectedByPassword.php (single_quote)
2) unit/EncodingTest.php (ordered_use)
```
> cleanup outdated dirs

- src/Key.php
- test/unit/BackwardsCompatibilityTest.php
the function loadFromRawBytesForTestingPurposesOnlyInsecure should only be used for unit testing. 
this PR removes the internal function and uses a closure to create a Key instance with the right key material.
> Remove Key::loadFromRawBytesForTestingPurposesOnlyInsecure

- src/Key.php
Without a leading backslash the type is interpreted relative to the current namespace.
> Fix return type of Key::createNewRandomKey()

- dist/Makefile
Unfortunately this didn't make it into 2.0.2, but that's okay because it only affects the next release process (and I double checked 2.0.2 still passes tests).
> Don't rebuild when signing the .phar

- docs/classes/Key.md
- src/Encoding.php
- src/Key.php
- test/unit/EncodingTest.php
This would prevent the errors present in #333 and #334. I don't believe removing newlines in variable time would ever introduce a practical timing leak, but I'll wait until @defuse sanity-checks this.
> Strip Newlines from ASCII-Safe Strings

- .travis.yml
- composer.json
- docs/InternalDeveloperDocs.md
- psalm.xml
- src/Core.php
- src/Crypto.php
- src/DerivedKeys.php
- src/Encoding.php
- src/File.php
- src/Key.php
- src/KeyOrPassword.php
- src/KeyProtectedByPassword.php
- src/RuntimeTests.php
This pull request uses [psalm](https://github.com/vimeo/psalm) to perform static analysis on every pull request and commit to master (as part of our Travis CI suite).
It also contains some idiomatic changes (e.g. `$var === false` -> `!\is_string($var)`).
> Add type safety analysis to Travis CI

- bin/generate-defuse-key
- composer.json
- docs/Tutorial.md
> [WIP] Add command line script for generating new keys

- .travis.yml
- src/File.php
See #374 for more info regarding this issue. Test suite passed on a PHP 7.2 env.
Resubmission from another branch.
> Allow hash_* methods to return a object to support PHP 7.2

- composer.json
- psalm.xml
- src/Encoding.php
For PHP 7+ software, we have a special tag at `v9.99.99` which is essentially empty. The purpose of this tag is to allow it to be loaded by Composer for PHP 7 software, and then not create conflicting definitions for static analysis tools and/or IDEs' type hinting.
See https://twitter.com/CiPHPerCoder/status/1004230888169852928
> Allow random_compat v9.99.99 on PHP 7 projects.

- dist/Makefile
This will make PHP Archive builds reproducible from the source code by eliminating nondeterminism via Composer's autoloader nonce.
> Make Phar builds reproducible

- src/Core.php
It is hard to diagnose the fail of some API, when the exception does not
contain a message. Having the reason of the fail, especially when a function or
a constant is missing, helps to fix an environment issue for example.
> Add message to some exceptions

- LICENSE
Github doesn't pick this up as MIT, made some minor changes for it to be identified correctly
> Normalise Licence file

- .travis.yml
- composer.json
- test/phpunit-10.xml
- test/phpunit-5.xml
- test/phpunit-8.xml
- test/phpunit.sh
- test/phpunit.xml
- test/unit/BackwardsCompatibilityTest.php
- test/unit/CoreTest.php
- test/unit/CryptoTest.php
- test/unit/CtrModeTest.php
- test/unit/EncodingTest.php
- test/unit/FileTest.php
- test/unit/KeyTest.php
- test/unit/LegacyDecryptTest.php
- test/unit/PasswordTest.php
- test/unit/RuntimeTestTest.php
Made PHPUnit tests pass in PHP 8.0, PHP 8.1 and PHP 8.2, by supporting PHPUnit 10, PHPUnit 8 and PHPUnit 5, complete with config files, one of which is explicitly picked by phpunit.sh based on the PHPUnit version previously determined based on the PHP version. This required dropping support for PHPUnit 4, but that is OK, as PHPUnit 5 still supports PHP 5.6, that being the earliest PHP version supported by this library.
Also fixed the broken exception message assertions in two of the tests, so that tests now pass.
> Made PHPUnit tests pass in PHP 8.0, PHP 8.1 and PHP 8.2
